version: "3.8"

volumes:
  tmp:
  public:
  data:
networks:
  web:
    driver: bridge

services:
  db:
    container_name: db
    image: mysql:8.0.31
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./tmp/db:/var/lib/mysql
      - data:/var/lib/mysql
      - ./infra/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - web

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
    stdin_open: true
    tty: true
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - .:/app
      - public:/app/public
      - tmp:/app/tmp
    # ports:
      # - "$API_PORT:3000"
    depends_on:
      - db
    networks:
      - web

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    volumes:
      - ./infra/web/nginx.conf:/etc/nginx/nginx.conf
      - public:/app/public
      - tmp:/app/tmp
    ports:
      - 8000:80
    depends_on:
      - app
    networks:
      - web