version: "3.8"

services:
  db:
    container_name: db
    image: mysql:8.0.31
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./infra/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - internal

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
    stdin_open: true
    tty: true
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
      BASE_URL: "http://localhost:$WEB_PORT"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      # - .:/app
      - ./app:/app
      - ./db:/db
      - ./spec:/spec
      - ./public:/public
      - ./tmp:/tmp
    depends_on:
      - db
    networks:
      - internal
      - external

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    volumes:
      - ./public:/public
      - ./tmp:/tmp
    ports:
      - 8000:80
    depends_on:
      - app
    networks:
      - external

volumes:
  tmp:
  public:

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
    internal: false